In [ ]:
import numpy as np
fitness_data = np.array([[5000, 200, 6]##>>25
                         ,[7000, 250, 7],##>> 28
                         [6500, 230, 6],##>28.26
                         [8000, 300, 8],##>>26.333
                         [9000, 320, 7],##>>28.125
                         [7500, 270, 6],##>>27.7778
                         [12000, 400, 5]]) ##>>30

6.428571428571429

In [ ]:
## dimension
fitness_data.ndim

2

In [ ]:
## shape
fitness_data.shape


(7, 3)

In [ ]:
#number of elements
fitness_data.size

21

In [ ]:
## all step values
fitness_data[:,0]

array([ 5000,  7000,  6500,  8000,  9000,  7500, 12000])

In [ ]:
### all calories values
fitness_data[:,1]

array([200, 250, 230, 300, 320, 270, 400])

In [ ]:
## all hours values
fitness_data[:,2]

array([6, 7, 6, 8, 7, 6, 5])

In [ ]:
## first 3 days
fitness_data[:3,:]

array([[5000,  200,    6],
       [7000,  250,    7],
       [6500,  230,    6]])

In [ ]:
## step&&calories
fitness_data[:,0:2]

array([[ 5000,   200],
       [ 7000,   250],
       [ 6500,   230],
       [ 8000,   300],
       [ 9000,   320],
       [ 7500,   270],
       [12000,   400]])

In [ ]:
## reshape step column
fitness_data[:,0].reshape(7,1)

array([[ 5000],
       [ 7000],
       [ 6500],
       [ 8000],
       [ 9000],
       [ 7500],
       [12000]])

In [ ]:
### reshape all data
fitness_data[:,:].reshape(3,7)

array([[ 5000,   200,     6,  7000,   250,     7,  6500],
       [  230,     6,  8000,   300,     8,  9000,   320],
       [    7,  7500,   270,     6, 12000,   400,     5]])

In [15]:
fitness_data[fitness_data[:,0]>8000]

array([[ 9000,   320,     7],
       [12000,   400,     5]])

In [16]:
fitness_data[fitness_data[:,2]<6]

array([[12000,   400,     5]])

In [17]:
fitness_data[fitness_data[:,1]>300]

array([[ 9000,   320,     7],
       [12000,   400,     5]])

In [ ]:
fitness_data[:,0].mean()

7857.142857142857

In [21]:
fitness_data[:,0].max()

12000

In [22]:
fitness_data[:,2].min()

5

In [27]:
fitness_data[:,1].std()

61.278887398649196

In [28]:
fitness_data[:,0].max()-fitness_data[:,0].min()

7000